### ISSUE TITLE
issue with refit

### ISSUE THREAD

**Issue by kori-time** [Pusheon/Nekos.Best-API#1]
PS C:\Users\xkori\Desktop\Nekos.Best-API-master\NekosBestApiNet> dotnet add package Refit --version 6.3.2
  Determining projects to restore...
C:\Program Files\dotnet\sdk\6.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): war
ning NETSDK1138: The target framework 'net5.0' is out of support and will not receive security updates in the future. P
lease refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\xkori\Deskto
p\Nekos.Best-API-master\NekosBestApiNet\NekosBestApiNet.csproj]
  Writing C:\Users\xkori\AppData\Local\Temp\tmp3BBC.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Adding PackageReference for package 'Refit' into project 'C:\Users\xkori\Desktop\Nekos.Best-API-master\NekosBestApiNet\NekosBestApiNet.csproj'.
info : Restoring packages for C:\Users\xkori\Desktop\Nekos.Best-API-master\NekosBestApiNet\NekosBestApiNet.csproj...
error: NU1101: Unable to find package Refit. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
error: NU1101: Unable to find package Microsoft.AspNetCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
error: NU1101: Unable to find package Microsoft.NETCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
error: NU1101: Unable to find package Microsoft.WindowsDesktop.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
error: Package 'Refit' is incompatible with 'all' frameworks in project 'C:\Users\xkori\Desktop\Nekos.Best-API-master\NekosBestApiNet\NekosBestApiNet.csproj'.
PS C:\Users\xkori\Desktop\Nekos.Best-API-master\NekosBestApiNet>

**Comment by SylveonDeko** [comment]
lemme see what .NET version it's using, if anything ill update it

**Comment by SylveonDeko** [comment]
Should be fixed, it now targets both net5 and net6
